### PR TITLE
Using shield icons for readme info

### PR DESCRIPTION
**Pull request by Thunderforge**
Moving version, license, Discord, and YouTube info into shields.

Shields

Note that Discord won't work unless [the Widget setting on the server is enabled](https://vimeo.com/364220040).

### CODE REVIEW

**Comment by Thunderforge** [comment]
If it's too busy, we could probably remove the MIT license since it appears prominently in both the desktop and mobile view. The releases are also visible, but you have to scroll to the bottom in the mobile view.

## Desktop
image

## Mobile top
image

## Mobile bottom
image

**Comment by afritz1** [comment]
Hmm neat. I wonder how well that would work with forks. I think you need to replace full URLs with just the local file in that case, like
```
[...](https://github.com/afritz1/OpenTESArena/blob/master/LICENSE.txt)
```
becomes
```
[...](LICENSE.txt)
```
I do it with the screenshot I think.

**Comment by Thunderforge** [comment]
I just checked and that does work to have a local file reference, but only when clicked from the Readme. If you click on it in this PR, it won't work.

The license image itself was dynamically queried from the repo. However, since the MIT license won't be changing any time soon, I can change it to a static label like so:

```
[![MIT License](https://img.shields.io/badge/license-MIT-green)](LICENSE.txt) 
```

[MIT License](LICENSE.txt)

**Comment by afritz1** [comment]
Okay cool. I'll turn on the Discord widget too.

**Comment by afritz1** [comment]
The `banner` part of the release shield seems to break the link.

**Comment by Thunderforge** [comment]
> The `banner` part of the release shield seems to break the link.

Fixed in #213

**Pull request merged**
