### PR TITLE
CMake: Use the CMake way to select C++11 standard

### PR DESCRIPTION
**Pull request by pcercuei**
Signed-off-by: Paul Cercueil <paul@crapouillou.net>

### CODE REVIEW

**Comment by afritz1** [comment]
Thanks for the change, @pcercuei. I'm still a little unsure about how to correctly use CMake yet. I don't quite have it working the way I'd like with Visual Studio. It's talked about in [this issue](https://github.com/afritz1/OpenTESArena/issues/17#issuecomment-226917415).

**Comment by kcat** [comment]
Unfortunately this breaks builds on older cmake versions. Debian is currently on cmake 3.0.2, and now building fails because it's not compiling with ```-std=c++11``` or equivalent anymore.

**Comment by Ragora** [comment]
And I've got 2.8.12 at the latest on Mint.

**Comment by pcercuei** [comment]
Seriously? CMake is at 3.5.2 now, you guys should update your systems :D
Maybe revert it for now then.

**Comment by Ragora** [comment]
@pcercuei My system is running the latest stable.

> ragora@Kiaro:~ > lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 17.3 Rosa
Release:        17.3
Codename:       rosa

https://www.linuxmint.com/download.php

There is a beta 18, but I try to just use stables.

**Pull request merged**
