### PR TITLE
Fixed ‘uint64_t’ does not name a type error preventing building on linux

### PR DESCRIPTION
**Pull request by IcePanorama**
Hello! I was attempting to build this project from scratch in order to make a contribution and I ran across this error while running `make`. Just made this simple, one-line fix for it and I was able to build the project without any issues.

### CODE REVIEW

**Comment by afritz1** [comment]
The original code compiles fine on my `sw-renderer-redesign-part-3` branch on like four flavors of Linux and on macOS. You should try that branch.

**Comment by IcePanorama** [comment]
Just tried it again on Fedora Linux 39/Kernel: 6.7.4-200.fc39.x86_64.

```bash
$ make -j8
[  0%] Building CXX object components/CMakeFiles/components.dir/debug/Debug.cpp.o
[  1%] Building CXX object components/CMakeFiles/components.dir/utilities/Bytes.cpp.o
[  1%] Building CXX object components/CMakeFiles/components.dir/archives/bsaarchive.cpp.o
[  1%] Building CXX object components/CMakeFiles/components.dir/utilities/Directory.cpp.o
[  2%] Building CXX object components/CMakeFiles/components.dir/utilities/FPSCounter.cpp.o
[  2%] Building CXX object components/CMakeFiles/components.dir/archives/archive.cpp.o
[  2%] Building CXX object components/CMakeFiles/components.dir/utilities/HexPrinter.cpp.o
[  2%] Building CXX object components/CMakeFiles/components.dir/utilities/File.cpp.o
[  2%] Building CXX object components/CMakeFiles/components.dir/utilities/KeyValueFile.cpp.o
[  3%] Building CXX object components/CMakeFiles/components.dir/utilities/Path.cpp.o
[  3%] Building CXX object components/CMakeFiles/components.dir/utilities/Profiler.cpp.o
[  3%] Building CXX object components/CMakeFiles/components.dir/utilities/String.cpp.o
[  4%] Building CXX object components/CMakeFiles/components.dir/utilities/StringView.cpp.o
[  4%] Building CXX object components/CMakeFiles/components.dir/utilities/TextLinesFile.cpp.o
[  4%] Building CXX object components/CMakeFiles/components.dir/utilities/VirtualHeap.cpp.o
[  5%] Building CXX object components/CMakeFiles/components.dir/vfs/manager.cpp.o
In file included from /home/[username]/Games/Open TESA/OpenTESArena/components/utilities/VirtualHeap.cpp:4:
/home/[username]/Games/Open TESA/OpenTESArena/components/utilities/VirtualHeap.h:19:32: error: ‘uint64_t’ does not name a type
   19 |                 using Offset = uint64_t;
      |                                ^~~~~~~~
... [more errors below] ...
```

Could just be a weird, one-off issue with my install perhaps.

Tried building the project with a `CMAKE_BUILD_TYPE` of `Debug` and `ReleaseNative`, but the problem still persists. I was able to fix it once again, however, just by including the `<cstdint>` library.

**Comment by afritz1** [comment]
Nah it's fine, it's just that I've fixed include errors for GCC like a hundred times on this engine so this is nothing new.

**Comment by afritz1** [comment]
I can try adding a Fedora VM to my list of systems to check. Is your setup unusual at all or should I just get the first ISO I see on the Fedora site?

**Comment by IcePanorama** [comment]
I'm using the [i3 WM spin version](https://fedoraproject.org/spins/i3/).

**Comment by afritz1** [comment]
It took a few tries but I got that installed and the engine compiled with latest `main`.

**Pull request merged**
