### PR TITLE
Job Manager

### LINKED ISSUE #245: Job system
The engine is lacking a good way of utilizing several threads. After the software rendering is optimized for single-threaded execution in part 3, it will switch to this job system so pixel shading, etc. can run 5-20x faster.

Off the top of my head, the job system needs a private thread pool and some kind of `addJob()`, `isRunning()`, and `wait()` functions. Maybe it could have a queue of `std::function<void()>` and worker threads would check if the queue is not empty. Later, `wait()` could take a category tag so it only waits for certain jobs to finish. Basically the job system exists so we don't have to use condition variables directly.

I am a bit shy of threading due to how easily bugs can show up, but the gains in the renderer and elsewhere would be massive.

### PR DESCRIPTION
**Pull request by lowercase-g**
This implements a job system (hopefully closes #245).

## Examples:

```c++
// If the job manager has at least 3 threads to work with, this 
// only takes 1 second.
{
    auto jm = JobManager(3);
    
    Job sleep ([](){ 
       std::this_thread::sleep_for(1000ms);
    });
    jm.submitJobs ( { sleep, sleep, sleep } );
}
// This, too, should only take 1 second.
{
    auto max_threads = std::thread::hardware_concurrency(); 
    auto jm = JobManager(max_threads);
    
    std::vector< Job > job_list (
       max_threads,
       Job( [](){ std::this_thread::sleep_for(1000ms); } )
    );
     
    jm.submitJobs ( job_list );
}
// This will wait for all jobs to be done before resuming the calling thread.
{
    auto max_threads = std::thread::hardware_concurrency(); 
    auto jm = JobManager(max_threads);
    
    Job sleep ([](){ 
       std::this_thread::sleep_for(1000ms);
    });
    
    jm.submitJobs( { sleep } );
    
    jm.wait();
    std::cout << "\nDone!";
}
``` 

Essentially, when a ``JobManager`` is constructed with an ``n_threads`` argument, it creates a private ``ThreadPool``.
That ``ThreadPool``, in turn, creates n_threads ``Workers``. 

``JobManager::run()`` spawns a background thread to do the following:
1) While the job queue is not empty, ask the thread pool for an idle worker. 

    If the thread pool can't immediately provide an idle worker, the background thread will wait until one is available. 

2) When an idle worker has been obtained, pop a job from the front of the queue and tell the idle worker to do it.

``JobManager``, if given a list of jobs in its constructor (optional), immediately starts running the job distributor.
Otherwise, ``JobManager::run()`` only runs when the following conditions are met:
1) ``JobManager::submitJobs()`` has been called.

2) ``JobManager::isRunning()`` returns false.

3) The job queue is not empty.

This means the only job-performing method you need to worry about is ``JobManager::submitJobs()``, and that adding jobs to an already-running queue is completely safe and intended behaviour: 
```c++
{
    auto jm = JobManager(std::thread::hardware_concurrency());
    
    Job sleep ([](){ 
       std::this_thread::sleep_for(1h);
    });
    // Since the queue was empty before, this starts the job system, 
    // which will run for an hour.
    jm.submitJobs ( { sleep } ); 
    // Completely safe, and a new instance of sleep has been appended to
    // jm's already-existing queue.
    jm.submitJobs ( { sleep } ); 
}
```

## To do: 

    [ ] Categories (filter which jobs JobManager::wait() waits for)
    [ ] Decentralize job distribution a bit more.

### CODE REVIEW

**Comment by afritz1** [comment]
Thanks. I'll start reviewing this tonight and push revisions. The Readme is not necessary.

**Comment by afritz1** [comment]
I need permission to write to your branch.
```Markdown
Enumerating objects: 54, done.
Counting objects: 100% (54/54), done.
Delta compression using up to 32 threads
Compressing objects: 100% (46/46), done.
Writing objects: 100% (47/47), 6.26 KiB | 6.26 MiB/s, done.
Total 47 (delta 34), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (34/34), completed with 5 local objects.        
remote: error: GH006: Protected branch update failed for refs/heads/Job-System.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/i-am-the-gabe/OpenTESArena.git
 ! [remote rejected]   pr/247 -> Job-System (protected branch hook declined)
error: failed to push some refs to 'https://github.com/i-am-the-gabe/OpenTESArena.git'
```

**Comment by i-am-the-gabe** [comment]
> I need permission to write to your branch.
> 
> ```gfm
> Enumerating objects: 54, done.
> Counting objects: 100% (54/54), done.
> Delta compression using up to 32 threads
> Compressing objects: 100% (46/46), done.
> Writing objects: 100% (47/47), 6.26 KiB | 6.26 MiB/s, done.
> Total 47 (delta 34), reused 0 (delta 0), pack-reused 0
> remote: Resolving deltas: 100% (34/34), completed with 5 local objects.        
> remote: error: GH006: Protected branch update failed for refs/heads/Job-System.        
> remote: error: At least 1 approving review is required by reviewers with write access.        
> To https://github.com/i-am-the-gabe/OpenTESArena.git
>  ! [remote rejected]   pr/247 -> Job-System (protected branch hook declined)
> error: failed to push some refs to 'https://github.com/i-am-the-gabe/OpenTESArena.git'
> ```

My bad, bungled the branch protection. Should work now.

**Comment by afritz1** [comment]
Okay, I made some changes to bring it more in line with what I'm looking for. Questions:
1. Can we fix the 'here be dragons'?
2. Can we make a `submitJob()` that takes one job? I think a common use case would be `submitJob(...); submitJob(...); submitJob(...); wait();`. It can use `submitJobs()` internally.
3. Can we allocate the ThreadPool without `std::unique_ptr`?
4. Can we fix the TODO on JobManager?

I'll handle # 2.

**Comment by afritz1** [comment]
Also I'm not sure if this is an easy change but `Worker::invoke()` should not create a new thread, it should reuse the `std::thread` it was initialized with. I don't want `std::this_thread::get_id()` changing for the same worker.

**Pull request closed without merging**
